# Site settings
title: 'ancientlore'
tagline: 'Michael D. Lore'
baseurl: "/" 
permalink:  "/:title"
domain: www.mlore.dev
github_username: ancientlore

defaults:
  - scope:
      path: "go-imports"
    values:
      layout: go-imports
      permalink: /:basename
      branch: master
